[{"bug_type":"MEMORY_LEAK","qualifier":"memory dynamically allocated by call to `malloc()` at line 16, column 16 is not reachable after line 19, column 5.","severity":"ERROR","line":19,"column":5,"procedure":"main","procedure_start_line":12,"file":"issue_1353-2.c","bug_trace":[{"level":0,"filename":"issue_1353-2.c","line_number":12,"column_number":1,"description":"start of procedure main()"},{"level":0,"filename":"issue_1353-2.c","line_number":14,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":16,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":17,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":19,"column_number":5,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":4,"column_number":1,"description":"start of procedure foo()"},{"level":1,"filename":"issue_1353-2.c","line_number":6,"column_number":9,"description":"Taking true branch"},{"level":1,"filename":"issue_1353-2.c","line_number":7,"column_number":9,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":6,"column_number":5,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":10,"column_number":1,"description":"return from a call to foo"}],"key":"issue_1353-2.c|main|MEMORY_LEAK","node_key":"03161a50ac98e07630986c44746b276f","hash":"07912ece3c593a5fad672fd0ec9f03b7","bug_type_hum":"Memory Leak"},{"bug_type":"NULL_DEREFERENCE","qualifier":"pointer `y` could be null and is dereferenced at line 21, column 18.","severity":"ERROR","line":21,"column":18,"procedure":"main","procedure_start_line":12,"file":"issue_1353-2.c","bug_trace":[{"level":0,"filename":"issue_1353-2.c","line_number":12,"column_number":1,"description":"start of procedure main()"},{"level":0,"filename":"issue_1353-2.c","line_number":14,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":16,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":17,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":19,"column_number":5,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":4,"column_number":1,"description":"start of procedure foo()"},{"level":1,"filename":"issue_1353-2.c","line_number":6,"column_number":9,"description":"Taking false branch"},{"level":1,"filename":"issue_1353-2.c","line_number":9,"column_number":9,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":6,"column_number":5,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":10,"column_number":1,"description":"return from a call to foo"},{"level":0,"filename":"issue_1353-2.c","line_number":21,"column_number":5,"description":""}],"key":"issue_1353-2.c|main|NULL_DEREFERENCE","node_key":"eb9d85fa6cef8459e8b39dba9551917e","hash":"5b20a6539574957a6e6c2962722479a8","bug_type_hum":"Null Dereference"},{"bug_type":"USE_AFTER_FREE","qualifier":"accessing memory that was invalidated by call to `free()` on line 19 indirectly during the call to `foo()()`.","severity":"ERROR","line":21,"column":18,"procedure":"main","procedure_start_line":12,"file":"issue_1353-2.c","bug_trace":[{"level":0,"filename":"issue_1353-2.c","line_number":19,"column_number":5,"description":"invalidation part of the trace starts here"},{"level":1,"filename":"issue_1353-2.c","line_number":19,"column_number":5,"description":"when calling `foo()` here"},{"level":2,"filename":"issue_1353-2.c","line_number":9,"column_number":9,"description":"memory was invalidated by call to `free()` here"},{"level":0,"filename":"issue_1353-2.c","line_number":17,"column_number":5,"description":"use-after-lifetime part of the trace starts here"},{"level":1,"filename":"issue_1353-2.c","line_number":17,"column_number":5,"description":"assigned"},{"level":1,"filename":"issue_1353-2.c","line_number":21,"column_number":18,"description":"invalid access occurs here"}],"key":"issue_1353-2.c|main|USE_AFTER_FREE","hash":"081cfab1e4ebece513ea15096b924713","bug_type_hum":"Use After Free"},{"bug_type":"USE_AFTER_FREE","qualifier":"pointer `y` was freed by call to `foo()` at line 19, column 5 and is dereferenced or freed at line 21, column 18.","severity":"ERROR","line":21,"column":18,"procedure":"main","procedure_start_line":12,"file":"issue_1353-2.c","bug_trace":[{"level":0,"filename":"issue_1353-2.c","line_number":12,"column_number":1,"description":"start of procedure main()"},{"level":0,"filename":"issue_1353-2.c","line_number":14,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":16,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":17,"column_number":5,"description":""},{"level":0,"filename":"issue_1353-2.c","line_number":19,"column_number":5,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":4,"column_number":1,"description":"start of procedure foo()"},{"level":1,"filename":"issue_1353-2.c","line_number":6,"column_number":9,"description":"Taking false branch"},{"level":1,"filename":"issue_1353-2.c","line_number":9,"column_number":9,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":6,"column_number":5,"description":""},{"level":1,"filename":"issue_1353-2.c","line_number":10,"column_number":1,"description":"return from a call to foo"},{"level":0,"filename":"issue_1353-2.c","line_number":21,"column_number":5,"description":""}],"key":"issue_1353-2.c|main|USE_AFTER_FREE","node_key":"eb9d85fa6cef8459e8b39dba9551917e","hash":"8ec6d04b34a26222e20edd4f557cd420","bug_type_hum":"Use After Free"}]
